"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import * as React from "react"
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import { Menu } from "lucide-react"
import Link from "next/link"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen">
        {/* Sidebar - shown always on desktop, sheet on mobile */}
        <aside className="hidden md:flex w-64 flex-col border-r bg-muted/40">
          <nav className="flex flex-col gap-2 p-4">
            <Link href="/scraper" className="font-medium">Home</Link>
            <Link href="/dashboard" className="font-medium">Tables</Link>
            <Link href="/credits" className="font-medium">Credits</Link>
          </nav>
        </aside>

        {/* Mobile Sidebar (Sheet) */}
        <div className="md:hidden">
          <Sheet>
            <SheetTrigger asChild>
              <Button variant="ghost" size="icon" className="m-2">
                <Menu className="h-5 w-5" />
              </Button>
            </SheetTrigger>
            <SheetContent side="left" className="w-64">
              <nav className="flex flex-col gap-4 mt-4">
                <Link href="/" className="font-medium">Dashboard</Link>
                <Link href="/projects" className="font-medium">Projects</Link>
                <Link href="/reports" className="font-medium">Reports</Link>
                <Link href="/settings" className="font-medium">Settings</Link>
              </nav>
            </SheetContent>
          </Sheet>
        </div>

        {/* Main content */}
        <main className="flex-1 p-5 overflow-auto">
          {children}
        </main>
      </body>
    </html>
  )
}
